[package]
name = "dynamixel_sdk_custom_interfaces"
version = "3.7.60"
edition = "2021"

[dependencies]
rosidl_runtime_rs = "0.3"
serde = { version = "1", optional = true, features = ["derive"] }
builtin_interfaces = "*"

[features]
serde = ['dep:serde', 'rosidl_runtime_rs/serde', 'builtin_interfaces/serde']
